name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" 
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: BANSAFAn
          outputs: snake.svg 
      - name: Commit snake SVG
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
