name: Update Typing SVG

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  update-typing-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install -g svg-term
        
      - name: Generate Typing SVG
        run: |
          curl -s "https://readme-typing-svg.herokuapp.com?font=Fira+Code&pause=1000&color=F7F7F7&center=true&vCenter=true&width=435&lines=Full-Stack+Developer;Open+Source+Enthusiast;Always+Learning+New+Things;Rust+%26+TypeScript+Lover;Building+the+Future;Solving+Problems+With+Code;Creating+Amazing+Experiences" > typing.svg
          
      - name: Push to repository
        uses: EndBug/add-and-commit@v7
        with:
          add: 'typing.svg'
          message: 'Update typing SVG'
          default_author: github_actions